<Project Sdk="Microsoft.NET.Sdk">
  <Sdk Name="Aspire.AppHost.Sdk" Version="9.1.0" />
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsAspireHost>true</IsAspireHost>
    <UserSecretsId>864eaa3d-4c88-4106-a53f-d34295182462</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Keycloak.Api.Weather\Keycloak.Api.Weather.csproj" />
    <ProjectReference Include="..\Keycloak.Web.BlazorSSR\Keycloak.Web.BlazorSSR.csproj" />
    <ProjectReference Include="..\Keycloak.Web.RazorPages\Keycloak.Web.RazorPages.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Hosting.AppHost" Version="9.1.0" />
    <PackageReference Include="Aspire.Hosting.Keycloak" Version="9.1.0-preview.1.25121.10" />
    <!--<PackageReference Include="Aspire.Hosting.Keycloak" Version="9.0.0-preview.5.24551.3" />-->
  </ItemGroup>

  <ItemGroup>
    <Folder Include="realms\" />
  </ItemGroup>

</Project>
